### ISSUE TITLE
Image tagging in Helm charts

### ISSUE THREAD

**Issue by staticvoid255** [openclarity/openclarity#169]
Hi there,

When deploying with Helm I would like to be able to pass a single version tag e.g. "v2.2.0" corresponding to the whole release rather than each image specifying their own versions respectively as it doesn't seem likely that someone would want 2.2.0 of one image but 2.1.0 for another. This is however all dependent on your release process and whether you think such cases will happen in the future i.e. when minor changes happen to one image but not another, but that doesn't look like what you're going for. Alternatives would be to use fixed version tags or enforce some kind of compatibility matrix.

Great project by the way!

**Comment by FrimIdan** [comment]
@staticvoid255 Hi, Thanks for your feedback.

The idea behind using different image tag per component was to make it easy for development to test changes that are related only for a single component.

I agree that the request `to be able to pass a single version tag` does make sense.
I think that we should make a single version tag in the `global.docker.imageTag` and we will update the current specific `imageTag` per component to be `imageName` (that will be empty be default) and will allow to overwrite the global params per component if needed.

Does this make more sense?

**Comment by staticvoid255** [comment]
Thanks for getting back to me.
Yep that's what I thought regarding why it is how it is right now. I was going to implement it myself but would involve changes to the configmap and deployment templates that I'd rather not have to maintain myself if possible.

Cheers!
