### ISSUE TITLE
Add a startTime and endTime to the AssetScan

### ISSUE THREAD

**Issue by ghost** [openclarity/openclarity#716]
I think we also need to add a startTime and endTime to the AssetScan itself. The start time should be set from the the moment the AssetScan moves from Pending to Scheduled and scanEndTime should be set when the AssetScan moves to Done or Failed. That will allow us to calculate the duration the AssetScan really took to scan from the point we start creating resources. We can also add cleanupEndTime, which is the point when the cleanup finishes which will give us the full e2e time for an AssetScan.

Adding these fields is something we need anyway in order to implement a per AssetScan timeout and I'm sure there are other use cases too.

_Originally posted by @sambetts-cisco in https://github.com/openclarity/vmclarity/pull/473#discussion_r1274864342_

**Comment by paralta** [comment]
already available at https://github.com/openclarity/openclarity/blob/main/api/openapi.yaml#L2920
