### ISSUE TITLE
Improve UI queries to reduce load time

### ISSUE THREAD

**Issue by FrimIdan** [openclarity/openclarity#720]
## Description

Not all the UI queries are using the `$select`, as a result, the waiting time for the page to load is longer than expected. 
For example, the following should improved
```
http://localhost:8889/api/scanResults/00ac1da0-cc08-49fb-b3b2-9a097da3523d?$expand=scan,scan/scanConfig,target
```

You can select the info you need
```
$select=status,summary
```

Or even sub-select from an expended field
```
$expand=scan/scanConfig($select=name,scheduled),scan($select=scanConfigSnapshot) 
```

There is a need to go over all UI queries to see how they can be improved.

## Expected Behavior

UI queries should not GET information the UI doesn't need

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by akijakya** [comment]
Done in https://github.com/openclarity/vmclarity/pull/1985
