### ISSUE TITLE
openclarity-scan Job Uses amd64 Only Curl Image

### ISSUE THREAD

**Issue by duckman** [openclarity/openclarity#886]
My kubernetes cluster is a mix of amd64 and arm64 nodes. The openclarity-scan jobs use yauritux/busybox-curl:latest to download assets. That image is 2 years old and is only amd64.
https://github.com/openclarity/openclarity/blob/9e20b24d929dd0a4842a18f05f2e3658dd2c49fd/provider/kubernetes/scanner/scanner.go#L189

I don't have a way to test another image but I would imagine the official curlimages/curl image would work?

**Comment by ramizpolic** [comment]
Hi @duckman, thanks for raising this. We will have this resolved in the next patch release
